# This action pushes new amd64 and arm64 docker images to the Docker and GitHub
# registries on every new release of the project.
#
# Cobbled together from these sources:
# - https://github.com/docker/build-push-action/#usage
# - https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: release

on:
  push:
    branches: [main]

  # uncomment this to enablle building for pull requests, to debug this
  # workflow.
  #
  # pull_request:
  #   branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for fastapi
        id: meta_fastapi
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/opamp-server-py/fastapi
          tags: |
            type=raw,value=latest
            type=sha
            type=semver,pattern={{version}}

      - name: Build and push fastapi
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.fastapi
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_fastapi.outputs.tags }}
          labels: ${{ steps.meta_fastapi.outputs.labels }}

      - name: Docker meta for streamlit
        id: meta_streamlit
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/opamp-server-py/streamlit
          tags: |
            type=raw,value=latest
            type=sha
            type=semver,pattern={{version}}

      - name: Build and push streamlit
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.streamlit
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_streamlit.outputs.tags }}
          labels: ${{ steps.meta_streamlit.outputs.labels }}
